[package]
name = "re_arc"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.5", features = ["std_rng"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
color-backtrace = "0.5.0"
